### ISSUE TITLE
Something about training time

### ISSUE THREAD

**Issue by Lan1991Xu** [imatge-upc/detection-2016-nipsws#10]
Hi all.
I train the pool45_crops_training.py, but it almost 4 days to get the mature model. I figure out, when the training stage, the GPU utilization is almost between 0 and 20%. So is there any wrong when i am training?
I environment is Keras 1.1 theano 0.8.2 CUDA7.5 CUDNN 5.0 python 2.7

**Comment by miriambellver** [comment]
Hi!

It also took some days for me. The GPU utilization is low because there is processing each time an action is performed, which is not performed on GPU. If you optimize it, let us know!

Míriam
