### ISSUE TITLE
Precision_recall Curve questions

### ISSUE THREAD

**Issue by yuanyuanjiao** [imatge-upc/detection-2016-nipsws#14]
Hi
#13 I saw Anida's problem. I have a same problem. And i can not get the precision recall curve from your paper.

I want to know what will u put the precision value and recall value if there are no proposals exceed the threshold you set? You set it to precision:1.0 recall: 0.0 or something else? I tried many methods. I evaulated it by getting each image's p_r value and let the average mean of them to the final p_r of this threshold. I also tried to caculate all the TP and FP and FN numbers of the whole testing images and used the formula to get the final p_r of this threshold. But also didn't get the result. This trapped me a lot.

You said 'I analyzed if any of them had more than 0.5 intersection over union with any object of the ground truth, and that is a TP'. but I think that means one gt can have more than one TP. 

And I want to know if your models given on github can be used directly to test and get the precision recall curve. Should i still need to train for getting the result of your paper.

You said this model is different from ones from your paper. One is for 1 object. One is for multiple objects. So did you have precision recall curve graph of this model ? 

Or if it is possible. Could you please upload the metric codes. That will be of great help.

Thanks a lot.

**Comment by whuhxb** [comment]
@yuanyuanjiao 
Hi!
Have you run this code both training and testing correctly?

**Comment by whuhxb** [comment]
@yuanyuanjiao 
Hi!
Have you obtained the AP, mAP, and PRC of this code?
