### ISSUE TITLE
Pre-trained model always select top-left region

### ISSUE THREAD

**Issue by zhangxiangnick** [imatge-upc/detection-2016-nipsws#2]
I used the pre-trained image-zooms model and tested on VOC2007 test. It runs properly, however, it seems that the agent just always take the same action ...

example:
![000216](https://cloud.githubusercontent.com/assets/10690183/20466598/0e593906-af2b-11e6-9a8f-103646b03e78.png)

I used the default config in image_zooms_testing.py:
```python
class_object = 1
# 1 if you want to obtain visualizations of the search for objects
bool_draw = 1
# Scale of subregion for the hierarchical regions (to deal with 2/4, 3/4)
scale_subregion = float(3)/4
scale_mask = float(1)/(scale_subregion*4)
# Number of steps that the agent does at each image
number_of_steps = 10
# Only search first object
only_first_object = 1
```

**Comment by miriambellver** [comment]
I see in the visualization that the q-value you are obtaining for each action is 'nan', and for this reason the action is always the same, the first one. The question is why you are obtaining nan... I can show you an example of visualization, you should see the estimated q-values related to each action, the final action selected, the mask of the region and the image region:

![example_000243](https://cloud.githubusercontent.com/assets/10169608/20466760/27cb5b82-af79-11e6-8b81-89332fcb98a0.png)

**Comment by zhangxiangnick** [comment]
I see. You are right, this step gives nan

``` python
qval = model.predict(state.T, batch_size=1)
```

I found np.sum(state) is nan for me, state is the default beginning state. Then I realized in the get_state() function,

``` python
descriptor_image = get_conv_image_descriptor_for_image(image, model_vgg)
```

gives nan at some elements.

**Comment by miriambellver** [comment]
maybe you should check if you are loading the vgg16 weights properly, I downloaded them from the following source: https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3

**Comment by zhangxiangnick** [comment]
Thanks @miriambellver !  After some investigations, I realized the problem is in this Theano function in get_conv_image_descriptor_for_image()
```python
_convout1_f = K.function(inputs, [model.layers[31].output])
```
which produces nan. 

To make it work, I actually switched to VGG16 from keras.applications and select the cooresponding Pool5 layer. Then the Theano function won't produce nan. This would require some changes of the requirement.txt as well.

If other people have the same issuees, I can submit all the details.

**Comment by NIEYALI** [comment]
Hello, @miriambellver , I met a problem, I installed theano and tensorflow, But when I run image_zooms_testing.py, It has a problem,"Using TensorFlow backend. and ValueError: Filter must not be larger than the input: Filter: (2, 2) Input: (1, 112)" Do you know what's the problem? thanks a lot
