### ISSUE TITLE
Something about training

### ISSUE THREAD

**Issue by FeiWard** [imatge-upc/detection-2016-nipsws#8]
When I training the model, it will be saved in the models_image_zooms folder at each epoch. But when I need to test the model, It need a full model instead of some epoch of it. Could you give me some advise to solve this problem~~~

**Comment by miriambellver** [comment]
At each epoch, the model is a 'full model' (as you call it). An epoch just means that the model has been trained seeing all the images of the database, but all these models at different epochs can be used...

**Comment by miriambellver** [comment]
I guess that the problem was solved, I close the ticket
