### ISSUE TITLE
adopt your solution to semantic segmentation

### ISSUE THREAD

**Issue by wenouyang** [imatge-upc/detection-2016-nipsws#9]
Hi, 

Thanks for sharing the code. I am curious whether this solution can help solve the binary semantic segmentation problem, such as the one given in https://www.kaggle.com/c/ultrasound-nerve-segmentation

If possible, what are the modifications that I have to make. Thanks a lot.

Yuanyuan

**Comment by miriambellver** [comment]
Hi! 

Our code tackles object detection. The actions are defined for this problem, discretizing the possible bounding boxes at each step. You should think how to define a set of actions useful to discretize the possible segmentations at each time step, which is not trivial.

Míriam

**Comment by wenouyang** [comment]
Thanks.
